Pisd 121/valencias fisicas
ToGatherGroup/front-sensei pull request #12
Opened 2024-03-30 23:29 UTC by Roberto-Mota

Adiciona tela "Listagem Avaliação" com itens hardcoded, além de criar um novo componente "ListItem" que pode ser utilizado com ou sem accordion (subItems).

Ainda requer routers configurados para as respectivas telas de cada item

2024-03-31 21:40 UTC, bruamado requested changes
Marquei no código um trecho que está quebrando o deploy.
No TypeScript, se você não tipar uma constante, ele tipa automaticamente com base nos valores passados na sua declaração.

2024-03-31 21:40 UTC, bruamado commented on src/app/avaliacao/page.tsx
> +                            <ListItem key={item.id} itemTitle={item.itemTitle} subItem={(item.subItem ? item.subItem : undefined)} />
O array de objetos indiceArray não possui a propriedade subItem dentro de seus objetos:
`const indiceArray = [
    {id: 1, itemTitle: 'IMC'},
]`

2024-04-01 10:59 UTC, Roberto-Mota commented on src/app/avaliacao/page.tsx
> +                            <ListItem key={item.id} itemTitle={item.itemTitle} subItem={(item.subItem ? item.subItem : undefined)} />
Adicionei a tipagem correta nos arrays 🚀

2024-04-01 11:00 UTC, Roberto-Mota commented on src/app/avaliacao/page.tsx
> +                            <ListItem key={item.id} itemTitle={item.itemTitle} subItem={(item.subItem ? item.subItem : undefined)} />
- Chequei aqui, o conteúdo está centralizado na página 👍🏽

2024-04-01 13:56 UTC, bruamado requested changes

2024-04-01 13:56 UTC, bruamado commented on src/app/avaliacao/page.tsx
> +                            <ListItem id={item.id} itemTitle={item.itemTitle} subItem={(item.subItem ? item.subItem : undefined)} />
Sempre que você estiver iterando (usando o map, por exemplo), o React exige que seja passada a Prop 'key' para o Fragment pai dentro do .map.

Vi que você tinha o key, e você acabou trocando por id, o que gerou um erro no deploy.
Precisa voltar aquela Key ali

`key={item.id}`

2024-04-02 01:41 UTC, bruamado approved these changes

2024-04-02 01:43 UTC, merged