feat: integration api chamada and atletas
ToGatherGroup/front-sensei pull request #18
Opened 2024-04-11 23:10 UTC by felipemarcelino99

2024-04-11 23:54 UTC, bruamado requested changes

2024-04-11 23:54 UTC, bruamado commented on src/components/listAthletes/index.tsx
> -    listAthletes: AthletesProps[];
Essa tipagem não aceita nulo,
A prop que vem e é atribuída a esta variável pode ser nula e por isso a chata da Vercel está quebrando o deploy

2024-04-12 00:40 UTC, felipemarcelino99 commented on src/components/listAthletes/index.tsx
> -    listAthletes: AthletesProps[];
Quem foi o chato dessa vez foi o typescript kkkk...resolvido

2024-04-12 00:47 UTC, bruamado commented on src/components/listAthletes/index.tsx
> +            const value = checkbox.value;
Typescript tá acusando que o value não existe no checkbox.
Você vai ter que tipar pra ele entender que é uma propriedade

2024-04-12 01:13 UTC, bruamado requested changes

2024-04-12 01:13 UTC, bruamado commented on src/contexts/api/api.tsx
>          return apiInstance.post(endpoint, body);
Esse método espera um object como body.

2024-04-12 01:13 UTC, bruamado commented on src/contexts/athlete/athlete.tsx
> +            const response = await post('atleta/chamada', JSON.stringify(ids));
Aqui você envia uma string

2024-04-13 22:42 UTC, bruamado approved these changes

2024-04-13 22:42 UTC, merged