Pisd 291/busca de relatorios
ToGatherGroup/front-sensei pull request #86
Opened 2024-07-10 15:41 UTC by Wilrrama

Renderiza no select um array de datas vindo da Api,

Ao receber a data, renderiza os dados que vem do Data, Ao clicar na o botão edição leva para o relatorio individual do atleta

2024-07-10 23:27 UTC, felipemarcelino99 requested changes
A função que você criou para fazer o GET, pode ser criada no context ou num hook customizado. Evita deixar lógica em telas/componentes.

Também pode remover o get do array de dependências do useEffect, ele reclama mas não da nada. Veja se isso já resolve o problema do loop. 

Também evita usar muitos useEffects, tenta trabalhar com props. useEffect é uma desgraça do react kkkk

2024-08-01 16:55 UTC, Roberto-Mota commented
Parece que essa branch está precisando de um rebase

2024-08-02 00:46 UTC, bruamado commented on public/icons/download.png
Este ícone o Michel mandou desnecessariamente grande

2024-08-02 00:46 UTC, bruamado commented on public/icons/edt.png
Este ícone o Michel mandou desnecessariamente grande

2024-08-02 00:46 UTC, bruamado commented on public/icons/report.png
Este ícone o Michel mandou desnecessariamente grande

2024-08-02 00:46 UTC, bruamado commented on src/schemas/evaluationSchema.ts
> +    .matches(/^\d{2}:\d{2}$/, "Tempo inserido é inválido.")
essa validação .matches fica desnecessária (redundante), uma vez que você já usou o .test abaixo e testou os segundos e minutos.

2024-08-02 00:46 UTC, bruamado commented on src/schemas/evaluationSchema.ts
> +    .matches(/^\d{2}:\d{2}$/, "Tempo inserido é inválido.")
Aqui é redundante também

2024-08-02 00:46 UTC, bruamado commented on src/schemas/evaluationSchema.ts
> +    .positive()
Como você já inseriu a validação `.min(1)`,
essa validação .positive() é desnecessária, uma vez que ele só irá aceitar números >= 1.

2024-08-02 00:46 UTC, bruamado commented on src/schemas/evaluationSchema.ts
> +    .min(1)
Aqui precisa inserir a mensagem de erro, senão ele cospe uma mensagem padrão em inglês:
![image](https://github.com/user-attachments/assets/1acbb1d9-081f-4ae8-aaa3-2fd03cb0e2bb)

2024-08-02 00:46 UTC, bruamado commented on src/schemas/evaluationSchema.ts
> +    .positive()
Como já existe `.min(1)`, a validação .positive é redundante.

2024-08-02 00:46 UTC, bruamado commented on src/schemas/evaluationSchema.ts
> +    .min(1)
Aqui precisa inserir a mensagem de erro, senão ele cospe uma mensagem padrão em inglês:
![image](https://github.com/user-attachments/assets/8dfe01f0-7bb0-4006-bae5-eb6286845a8d)

2024-08-02 00:46 UTC, bruamado commented on src/schemas/evaluationSchema.ts
> +    .positive()
Especificar mensagem de erro:
![image](https://github.com/user-attachments/assets/d12a34da-404e-4118-b6a4-ff786435cb56)

2024-08-02 00:46 UTC, bruamado commented on src/schemas/evaluationSchema.ts
> +    .positive()
Especificar mensagem de erro:
![image](https://github.com/user-attachments/assets/a1d32f7f-60cc-4497-8efe-a887af50d09c)

2024-08-02 00:46 UTC, bruamado commented on src/schemas/evaluationSchema.ts
> +    .positive()
Especificar mensagem de erro:
![image](https://github.com/user-attachments/assets/64e543b6-634d-43bc-a6c7-e3d710e66bec)

2024-08-02 00:46 UTC, bruamado commented on src/schemas/evaluationSchema.ts
> +    .positive()
Especificar mensagem de erro:
![image](https://github.com/user-attachments/assets/2a76eb0f-7983-43d6-9714-ada983c9edf6)

2024-08-02 00:46 UTC, bruamado commented on src/components/evaluationForm/index.tsx
> +  const [exercicios, setExercicios] = useState<IEvaluationData | null>(null);
Você criou este useState, mas não usou

2024-08-02 00:46 UTC, bruamado commented on src/components/evaluationForm/index.tsx
> +  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
Você poderia ter feito esse tratamento utilizando máscara (biblioteca iMask), assim como você fez no input "Prancha"

2024-08-02 00:46 UTC, bruamado commented on src/components/evaluationForm/index.tsx
> +  const handleInput = (e: React.FormEvent<HTMLInputElement>) => {
Você poderia ter feito esse tratamento utilizando máscara (biblioteca iMask), assim como você fez no input "Prancha"

2024-08-02 00:46 UTC, bruamado commented on src/components/evaluationForm/index.tsx
> +  const handleKeyDownLounge = (e: React.KeyboardEvent<HTMLInputElement>) => {
Você poderia ter feito esse tratamento utilizando máscara (biblioteca iMask), assim como você fez no input "Prancha"

2024-08-02 00:46 UTC, bruamado commented on src/components/evaluationForm/index.tsx
> +  const handleInputLounge = (e: React.FormEvent<HTMLInputElement>) => {
Você poderia ter feito esse tratamento utilizando máscara (biblioteca iMask), assim como você fez no input "Prancha"

2024-08-02 00:46 UTC, bruamado commented on src/components/evaluationForm/index.tsx
> +              setExercicios(exerciciosData);
Você alimenta esse useState, mas nunca usa o valor alimentado

2024-08-02 00:46 UTC, bruamado commented on src/components/evaluationForm/index.tsx
> +      switch (method) {
Já que este Switch só tem um Case, ele poderia ser substituído por um simples if

2024-08-02 00:46 UTC, bruamado commented on src/components/evaluationForm/index.tsx
> +  function minSecToPT(time: string | null): Time | null {
Eu fiz uma função que faz basicamente a mesma coisa,
você poderia importar ela e usar, a fim de reaproveitar código:

![image](https://github.com/user-attachments/assets/c76f6265-0dd6-4579-8e03-a5886d2331c1)
![image](https://github.com/user-attachments/assets/80653fbe-0bf6-4495-aebb-54828d449545)

2024-08-02 00:46 UTC, bruamado commented on src/components/evaluationForm/index.tsx
> +              <input
Sempre que for um input que somente irá aceitar números, precisamos nos atentar para os dispositivo mobile.
O ideal é que o celular exiba somente aquele teclado número, sem exibir teclas com letras que não podem ser inseridas.
Para que isso aconteça, precisamos adicionas as seguintes propriedades HTML a tag <input>
![image](https://github.com/user-attachments/assets/b9a3ce95-e22b-4003-8e90-b207ec14e60a)


Podemos setar também o `type="number"` mas isso precisa ser bem analisado, uma vez que esse type costuma inserir um step button, e muitas vezes não é compatível com algumas bibliotecas como por exemplo o iMask.

2024-08-02 00:46 UTC, bruamado commented on src/components/evaluationForm/index.tsx
> +            {method === "PUT" ? (
Já que a única coisa deste botão que muda a depender do método, é o texto, ele poderia ter sido feito de uma maneira mais simples:

Ao invés de:
`{method === "PUT" ? (
              <Button type={"submit"} text={"Alterar"} />
            ) : (
              <Button type={"submit"} text={"Cadastrar"} />
            )}`

Poderia ter sido feito assim:
`<Button type={"submit"} text={method === "PUT" ? "Alterar" : "Cadastrar} />`

2024-08-02 14:21 UTC, Wilrrama commented on src/components/evaluationForm/index.tsx
> +              setExercicios(exerciciosData);
ele é alimentado no modo de edição

2024-08-02 19:48 UTC, bruamado reviewed
Falta somente a correção das mensagens de erro no Yup que estão sendo exibidas em inglês

2024-08-02 21:28 UTC, ToGatherGroup approved these changes
Aprovado!
Pode fazer o Merge!

2024-08-02 22:23 UTC, merged